frontend/models/Member.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "member".
 *
 * @property int $member_id
 * @property int $faculty_id
 * @property int $branch_id
 * @property string $member_username
 * @property string $member_password
 * @property string $member_profile_pic
 * @property string $member_firstname
 * @property string $member_lastname
 * @property string $member_tel
 * @property string $member_type
 *
 * @property RequestClassroom[] $requestClassrooms
 */
class Member extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'member';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['faculty_id', 'branch_id'], 'integer'],
            [['member_username', 'member_password', 'member_firstname', 'member_lastname', 'member_tel', 'member_type'], 'required'],
            [['member_username', 'member_tel'], 'string', 'max' => 15],
            [['member_password'], 'string', 'max' => 50],
            [['member_profile_pic'], 'string', 'max' => 255],
            [['member_firstname', 'member_lastname'], 'string', 'max' => 100],
            [['member_type'], 'string', 'max' => 30],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'member_id' => 'ไอดี',
            'faculty_id' => 'คณะ',
            'branch_id' => 'สาขา',
            'member_username' => 'รหัสผู้ใช้งาน',
            'member_password' => 'รหัสผ่าน',
            'member_profile_pic' => 'รูปโปรไฟล์',
            'member_firstname' => 'ชื่อ',
            'member_lastname' => 'นามสกุล',
            'member_tel' => 'เบอร์โทรศัพท์',
            'member_type' => 'ประเภทผู้ใช้งาน',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestClassrooms()
    {
        return $this->hasMany(RequestClassroom::className(), ['member_id' => 'member_id']);
    }
}

frontend/controllers/MemberController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\models\Member;

class MemberController extends Controller {
    public function actionMember() {
        $mem = Member::find()->all();
        return $this->render('member',['mem' => $mem]);
    }
    public function actionMembercreate(){
        $model = new Member;
        if(Yii::$app->request->post()) {
            $model->load(Yii::$app->request->post());
            if($model->save()) {
                return $this->redirect(['member']);
            }
        }
        
        return $this->render('membercreate' ,['model' => $model]);
    }
    public function actionMemberupdate($id) {
        $model = Member :: findOne($id);
        if(Yii::$app->request->post()) {
            $model->load(Yii::$app->request->post());
            if($model->save()) {
                return $this->redirect(['member']);
            }
        }
        return $this->render('memberupdate',['model' => $model]);
    }
    public function actionMemberdelete($id) {
        $model = Member :: findOne($id);

        if($model->delete()) {
            return $this->redirect(['member']);
        } else{
            echo 'fail...';
        }
    }
}

frontend/views/member/formmember.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<div class="well">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'faculty_id')->textInput(); ?>
    <?= $form->field($model, 'branch_id')->textInput(); ?>
    <?= $form->field($model, 'member_username')->textInput(); ?>
    <?= $form->field($model, 'member_password')->textInput(); ?>
    <?= $form->field($model, 'member_profile_pic')->textInput(); ?>
    <?= $form->field($model, 'member_firstname')->textInput(); ?>
    <?= $form->field($model, 'member_lastname')->textInput(); ?>
    <?= $form->field($model, 'member_tel')->textInput(); ?>
    <?= $form->field($model, 'member_type')->textInput(); ?>
    
    <?=Html :: submitButton('คกลง',['class' => 'btn btn-success'])?>
    <?php $form = ActiveForm::end(); ?>
</div>

frontend/views/member/member.php
<?php
use yii\helpers\Url;
use yii\web\View;
?>
<a href="<?= Url::to(['member/membercreate']); ?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>เพิ่มข้อมูล</a>
<div style="height:10px;"></div>

<table class="table">
    <thead style="background-color: #5cb85c;">
        <tr>
            <th>ไอดี</th>
            <th>คณะ</th>
            <th>สาขา</th>
            <th>รหัสผู้ใช้งาน</th>
            <th>รหัสผ่าน</th>
            <th>รูปโปรไฟล์</th>
            <th>ชื่อ</th>
            <th>นามสกุล</th>
            <th>เบอร์โทรศัพท์</th>
            <th>ประเภทผู้ใช้งาน</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($mem as $key => $memm) : ?>
        <tr>
            <td><?= $memm->member_id; ?></td>
            <td><?= $memm->faculty_id; ?></td>
            <td><?= $memm->branch_id; ?></td>
            <td><?= $memm->member_username; ?></td>
            <td><?= $memm->member_password; ?></td>
            <td><?= $memm->member_profile_pic; ?></td>
            <td><?= $memm->member_firstname; ?></td>
            <td><?= $memm->member_lastname; ?></td>
            <td><?= $memm->member_tel; ?></td>
            <td><?= $memm->member_type; ?></td>
            <td>
                <a href="<?= Url::to(['member/memberupdate', 'id'=> $memm->member_id]); ?>"><i class="glyphicon glyphicon-pencil"></i></a> | 
                <a href="<?= Url::to(['member/memberdelete', 'id'=> $memm->member_id]); ?>" class="delete"><i class="glyphicon glyphicon-trash"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php

$this->registerJS("
    $('.delete').click(function() { 
        if(!confirm('Please confirm')){
            return false;
        }
    });
");
?>

frontend/views/member/membercreate.php
<h2>เพิ่มข้อมูลสมาชิก</h2>
<?php
echo $this->render('formmember' ,['model' => $model]); 

frontend/views/member/memberupdate.php
<h2>แก้ไขข้อมูลสมาชิก</h2>
<?php
echo $this->render('formmember' ,['model' => $model]); 